MINUTOSTRABAJADOSPORDIA=float(input("Ingrese minutos trabajados por dia:"))
VALORPORHORA=float(input("Ingrese valor por hora:"))
HORASTRABAJADASPORDIA=MINUTOSTRABAJADOSPORDIA/60
SUELDOPORDIA=HORASTRABAJADASPORDIA*VALORPORHORA
SUELDOMENSUAL=SUELDOPORDIA*30
print("Sueldo Mensual:")
print(SUELDOMENSUAL)
 
